package eu.revq.commands

enum class CommandId {
    StartReviewSession,
    MarkSelectedReviewed,
    UndoLastReviewed,
    PreviousReview,
    NextReview,
    EndReviewSession,
    OpenSelectedPrInGitHub,
    CopySelectedPrUrl,
    CopySelectedPrMarkdown,
    CopyReviewQueueDigest,
    ToggleSelectedPrPin,
    OpenTopReviewPullRequests,
    OpenSelectedRepository,
    ToggleMuteSelectedRepository,

    GoToNeedsReview,
    GoToMyPullRequests,
    GoToPinned,
    GoToToday,
    GoToBlocked,
    GoToReady,
    GoToReviewed,
    GoToSettings,

    Refresh,
    ClearFilter,
    ToggleGroupByRepository,
    ToggleCompactRows,
    CycleSortMode,
    TestGitHubCli,
    DiscoverRepositories,
    ToggleFocusReviewMode,
    PreviewReminder,
    CopyDiagnostics,
    ShowKeyboardShortcuts,
}
